version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make test_requirements
            make test
  flake8:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run flake8
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8
            flake8
  publish_to_pypi:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make test_requirements
            make publish

workflows:
  version: 2
  test_and_publish_to_pypi:
    jobs:
      - test
      - flake8
      - publish_to_pypi:
          requires:
            - test
            - flake8
          filters:
            branches:
              only: master
